name: 🐞 Ab module bug report 
description: Report errors or unexpected behaviors for the Ab module.
labels: [needs-triage, bug]

body:
- type: markdown
  attributes:
    value: >
      Thanks for reporting the bug you have discovered.

      - Make sure you are able to reproduce this issue on the latest released version of [Ab](https://www.powershellgallery.com/packages/Ab)
      
      - Please search the existing issues to see if there has been a similar issue filed
- type: textarea
  attributes:
    label: Description
    description: >
      Please describe the issue and expected result. Please paste error script to next "Debug output" section 
  validations:
    required: true
- type: textarea
  attributes:
    label: Issue script & Debug output
    description: >
      Set `$DebugPreference='Continue'` before running the repro and paste the resulting debug stream in the below textarea

      **⚠ ATTENTION:** Be sure to remove any sensitive information that may be in the logs
    render: PowerShell
    placeholder: |
      PS> $DebugPreference='Continue'
      PS> {}-Ab{} ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment data
    description: >
      Please run `$PSVersionTable` and paste the output in the below textarea.
      If running the Docker container image, indicate the tag of the image used and the version of Docker engine
    render: PowerShell
    placeholder: |
      PS> $PSVersionTable
  validations:
    required: true
- type: textarea
  attributes:
    label: Module versions
    description: >
      Please run `Get-Module Ab*` after cmdlet execution and paste the output in the below textarea.

      If module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.
    render: PowerShell
    placeholder: |
      PS> Get-Module Ab*
  validations:
    required: true
- type: textarea
  attributes:
    label: Error output
    description: >
      Please run `Resolve-AbError` and paste the output in the below textarea

      **⚠ ATTENTION:** Be sure to remove any sensitive information that may be in the logs
    render: PowerShell
    placeholder: |
      PS> Resolve-AbError
  validations:
    required: false